export { App } from './App.ts';
export {
  ActivePatternsModal,
  AuthButton,
  FileDropZone,
  ImageImportModal,
  LoginModal,
  Palette,
  PatternCanvas,
  PatternGalleryModal,
  TopBar,
} from './components';
export {
  convertImageToPattern,
  DEFAULT_OPTIONS,
  getImageDimensions,
  isImageFile,
} from './converters';
export type { ImageConversionOptions } from './converters';
export {
  colorDistance,
  DMC_COLORS,
  findByCode,
  findByHex,
  findByName,
  findByRgb,
  findClosestDMC,
  findClosestDMCColors,
  findClosestDMCWithDistance,
  findDMC,
  getAllCodes,
  getColorCount,
  getColorFamily,
  loadPatternFile,
  patternCatalog,
  rgbToHex,
  searchByName,
} from './data';
export type { DMCColor, PatternCatalogEntry } from './data';
export { useAuth, useAutosaveSnapshots } from './hooks';
export { parseFCJSON, parseOXS, parsePatternFile } from './parsers';
export {
  checkCompletion,
  countAnyStitches,
  createInitialProgress,
  deleteLocalSnapshots,
  deletePattern,
  deleteProgress,
  fromPersisted,
  getAllPatternsWithProgress,
  getDB,
  listLocalSnapshots,
  loadLocalSnapshot,
  loadPattern,
  loadProgress,
  persistedToU16,
  persistedToU8,
  saveLocalRollingSnapshot,
  savePattern,
  saveProgress,
  toPersisted,
  u16ToPersisted,
  u8ToPersisted,
  useGameStore,
} from './store';
export type {
  GameState,
  NavigationRequest,
  PersistedPattern,
  PersistedProgress,
  PersistedSnapshot,
} from './store';
export {
  assignSymbolsForPalette,
  DEFAULT_SYMBOL_OPTIONS,
  isSingleCodeUnitSymbol,
  isValidPoolSymbol,
  MAX_PALETTE_SIZE,
  SYMBOL_POOL,
  validateSymbolPool,
} from './symbols';
export type { SymbolAssignOptions } from './symbols';
export {
  base64ToBytes,
  BUCKET,
  bytesToBase64,
  decodeProgressSnapshot,
  encodeProgressSnapshot,
  gzipCompress,
  gzipDecompress,
  listRemoteSlots,
  loadLatestRemoteSnapshot,
  MAX_SLOTS,
  parseSlot,
  pickSlotToWrite,
  saveRemoteRollingSnapshot,
  signInWithEmailOtp,
  signOut,
  slotPath,
  snapshotToProgress,
  supabase,
  u16ToBase64,
} from './sync';
export type { ProgressSnapshotV1, RemoteSlot } from './sync';
export { NO_STITCH, StitchState } from './types';
export type {
  GridCell,
  PaletteCounts,
  PaletteEntry,
  PatternDoc,
  PatternMeta,
  Point,
  ToolMode,
  UserProgress,
  ViewportTransform,
} from './types';
export {
  calculateFitViewport,
  CELL_SIZE,
  cellSeed,
  clampViewport,
  createOffscreenCanvas,
  createSeededRandom,
  drawFabricBackground,
  drawRealisticStitch,
  drawSymbol,
  drawThreadStrand,
  drawWrongIndicator,
  FABRIC_COLOR,
  FABRIC_HOLE_COLOR,
  getCellRandoms,
  getViewportCenterInGrid,
  getVisibleGridBounds,
  gridCenterToScreen,
  gridToWorld,
  hashString,
  hexToRgb,
  NOT_A_TARGET,
  renderCanvas,
  rgbToString,
  screenToGrid,
  screenToWorld,
  SELECTED_COLOR_HIGHLIGHT,
  SYMBOL_COLOR,
  TILE_SIZE,
  UnstitchedIndex,
  worldToGrid,
  worldToScreen,
} from './utils';
export type { ColorIndex, RenderContext } from './utils';
